### ISSUE TITLE
Messed up cheksums in 0.12.1 release 

### ISSUE THREAD

**Issue by unsystemizer** [btcdrak/bitcoin#9]
In v0.12.1 (https://github.com/btcdrak/bitcoin/releases/tag/v0.12.1-addrindex):
- Hashes used are supposedly SHA512

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Bitcoin Core 0.12.1-addrindex

72fad8e5a256a263303d7f1424b61c42a36997a778367ddeafcc6ff19b71d656  bitcoin-0.12.1-linux32.tar.gz
77da81fd491cb76eeb6c195435b3917f2bba6ba684557a9caaa6a21de585d54b  bitcoin-0.12.1-linux64.tar.gz
5222664516d5d61aac710913040ea4778613b7e2c27dbcf20b3f9f48a30655e9  bitcoin-0.12.1.tar.gz
```

But string next to the second package, for example, matches its sha256 (not sha512) checksum.

```
# sha256sum bitcoin-0.12.1-linux64.tar.gz
77da81fd491cb76eeb6c195435b3917f2bba6ba684557a9caaa6a21de585d54b  bitcoin-0.12.1-linux64.tar.gz
```
- Some packages (like https://github.com/btcdrak/bitcoin/archive/v0.12.1-addrindex.zip) have no checksum at all
- At least one package, `v0.12.1-addrindex.tar.gz`, has a sha256 checksum that's wrong. I downloaded it twice and release notes claim it's `5222664516d5d61aac710913040ea4778613b7e2c27dbcf20b3f9f48a30655e9` whereas on my client it computes to `454d8780089428cb28e18ad0fde9235557d125a2c3469f1b054a674314ef5b89`

```
# sha256sum v0.12.1-addrindex.tar.gz
454d8780089428cb28e18ad0fde9235557d125a2c3469f1b054a674314ef5b89  v0.12.1-addrindex.tar.gz
```

**Comment by btcdrak** [comment]
> Hashes used are supposedly SHA512

They are sha256, the PGP signature using SHA512 digest.

> At least one package, v0.12.1-addrindex.tar.gz, has a sha256 checksum that's wrong. 

These are source archives created by github itself and there are no listed hashes for it. The hashes are the result of the gitian building process. They dont need to be hashed since source is easily verifiable from from the signed git tag.

What I did notice is I didnt add `-addrindex` into the filename, which I'll go ahead and do. It'll require redoing the signature, but the hashes remain the same.
